import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './_providers/providers';
import { ThreeBackground } from '@/components/three/ThreeBackground';

export const metadata: Metadata = {
  title: 'Jaurnalist - AI-Powered News Platform',
  description: 'Real-time news generated by AI journalists, reviewed by AI editors.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen antialiased">
        <Providers>
          <ThreeBackground />
          <div className="relative z-10">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
